name: cyber_todo
description: A Flutter Todo App with Cyber Dev Aesthetic and Google Sign-In

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.6
  uuid: ^4.3.3
  intl: any
  flutter_local_notifications: ^19.3.0
  flutter_launcher_icons: ^0.13.1
  badges: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_icon.png
    - assets/images/google.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png



